### ISSUE TITLE
U-Turn assertion triggered in osrm-extract

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2101]
When running #1935 on an data extract from the bay area the following assertion is triggered:

```
#6  0x00000000007a6a7e in osrm::extractor::EdgeBasedGraphFactory::Run (this=this@entry=0x7fffffffad50, 
    original_edge_data_filename="/home/patrick/Code/osrm-data/bay_area_2015-08-14-2.osrm.edges", lua_state=lua_state@entry=0xabbb88, 
    edge_segment_lookup_filename="/home/patrick/Code/osrm-data/bay_area_2015-08-14-2.osrm.edge_segment_lookup", 
    edge_penalty_filename="/home/patrick/Code/osrm-data/bay_area_2015-08-14-2.osrm.edge_penalties", generate_edge_lookup=<optimized out>)
    at /home/patrick/Code/osrm-temp/src/extractor/edge_based_graph_factory.cpp:178
#7  0x000000000072c965 in osrm::extractor::Extractor::BuildEdgeExpandedGraph (this=this@entry=0x7fffffffe1d0, 
    internal_to_external_node_map=std::vector of length 892232, capacity 1048576 = {...}, node_based_edge_list=std::vector of length 0, capacity 0, 
    node_is_startpoint=std::vector<bool> of length 0, capacity 0, edge_based_node_weights=std::vector of length 0, capacity 0, edge_based_edge_list=...)
    at /home/patrick/Code/osrm-temp/src/extractor/extractor.cpp:536
#8  0x000000000072df9e in osrm::extractor::Extractor::run (this=this@entry=0x7fffffffe1d0) at /home/patrick/Code/osrm-temp/src/extractor/extractor.cpp:272
#9  0x00000000006e6d2b in main (argc=4, argv=0x7fffffffe4e8) at /home/patrick/Code/osrm-temp/src/tools/extract.cpp:147
(gdb) f 3
#3  0x00000000007cdd4d in osrm::extractor::guidance::TurnAnalysis::handleTwoWayTurn (this=this@entry=0x7fffffffa320, from=from@entry=686395, via_edge=via_edge@entry=1461569, 
    turn_candidates=std::vector of length 2, capacity 4 = {...}) at /home/patrick/Code/osrm-temp/src/extractor/guidance/turn_analysis.cpp:843
843     BOOST_ASSERT(turn_candidates[0].angle < 0.001);
(gdb) p turn_candidates 
$1 = std::vector of length 2, capacity 4 = {{eid = 1462389, valid = true, angle = 173.75692378118558, instruction = {type = osrm::extractor::guidance::Turn, 
      direction_modifier = osrm::extractor::guidance::Straight}, confidence = 0.61023999326073808}, {eid = 1462388, valid = false, angle = 352.42446784161132, instruction = {
      type = osrm::extractor::guidance::Invalid, direction_modifier = osrm::extractor::guidance::UTurn}, confidence = 0}}
```

As you can see the assertion hits because the u-turn is not the first candidate.

**Comment by TheMarex** [comment]
Fixed.
