### ISSUE TITLE
Edge Update Tests Break on Cache

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2965]
When running cucumber tests for edge-weight-updates for the first time, the test succeeds fine.

```
cucumber features/options/contract/edge-weight-updates-over-factor.feature:6
Node Version v4.0.0
@contract @options @edge-weight-updates-over-factor
Feature: osrm-contract command line option: edge-weight-updates-over-factor

  @contract @options @edge-weight-updates-over-factor
  Scenario: Logging weight with updates over factor of 2, long segment
    Given the node locations
      | node | lat | lon |
      | a    | 0.1 | 0.1 |
      | b    | .05 | 0.1 |
      | c    | 0.3 | 0.1 |
    And the ways
      | nodes | highway     |
      | ab    | residential |
      | ac    | primary     |
    Given the profile "testbot"
    Given the extract extra arguments "--generate-edge-lookup"
    Given the speed file
      """
      1,2,100
      1,3,100
      """
    And the data has been extracted
    When I run "osrm-contract --edge-weight-updates-over-factor 2 --segment-speed-file {speeds_file} {processed_file}"
    And stderr should contain "weight updates"
    And stderr should contain "New speed: 100 kph"
    And I route I should get
      | from | to | route | speed    |
      | a    | b  | ab,ab | 100 km/h |
      | a    | c  | ac,ac | 100 km/h |

1 scenario (1 passed)
10 steps (10 passed)
0m00.926s
```

On all succeeding runs, I consistently see the following error.

```
Node Version v4.0.0
@contract @options @edge-weight-updates-over-factor
Feature: osrm-contract command line option: edge-weight-updates-over-factor

  @contract @options @edge-weight-updates-over-factor
  Scenario: Logging weight with updates over factor of 2, long segment
    Given the node locations
      | node | lat | lon |
      | a    | 0.1 | 0.1 |
      | b    | .05 | 0.1 |
      | c    | 0.3 | 0.1 |
    And the ways
      | nodes | highway     |
      | ab    | residential |
      | ac    | primary     |
    Given the profile "testbot"
    Given the extract extra arguments "--generate-edge-lookup"
    Given the speed file
      """
      1,2,100
      1,3,100
      """
    And the data has been extracted
    When I run "osrm-contract --edge-weight-updates-over-factor 2 --segment-speed-file {speeds_file} {processed_file}"
    And stderr should contain "weight updates"
    And stderr should contain "New speed: 100 kph"
    And I route I should get
      | from | to | route | speed    |
      | a    | b  | ab,ab | 100 km/h |
      | a    | c  | ac,ac | 100 km/h |

Failures:

1) Scenario: Logging weight with updates over factor of 2, long segment - features/options/contract/edge-weight-updates-over-factor.feature:6
   Step: And stderr should contain "weight updates" - features/options/contract/edge-weight-updates-over-factor.feature:25
   Step Definition: features/step_definitions/options.js:63
   Message:
     AssertionError: false == true
         at World.<anonymous> (/Users/mokob/git/engine/project-osrm/osrm-backend/features/step_definitions/options.js:64:16)
         at doNTCallback0 (node.js:407:9)
         at process._tickCallback (node.js:336:13)

1 scenario (1 failed)
10 steps (1 failed, 2 skipped, 7 passed)
0m00.242s
```

It seems that the check does not work well with caching.

**Comment by oxidase** [comment]
@MoKob the test check will not work with caching. 

At the first test run:
* "And the data has been extracted"
   -  no extract stamp -> `osrm-extract` runs -> extract stamp created
   - no contract stamp -> `osrm-contract` runs -> contract stamp created
* "When I run "osrm-contract .."
   - no stamp check, osrm-contract runs, .geometry is updated the first time, the check **passes**
* "And I route I should get"
  - extract stamp  check -> no `osrm-extract` run
  - contract stamp check ->  no `osrm-extract` run

The second test run:
* "And the data has been extracted"
   -  extract stamp checked -> no `osrm-extract` run
   - contract stamp checked -> no `osrm-contract` run
* "When I run "osrm-contract .."
   - no stamp check, osrm-contract runs, .geometry file is updated **the second time**, the check **fails**

A temp workaround for the test  is to add osrm-extract run without a cache check
```
        When I run "osrm-extract --profile {profile_file} {osm_file}"
        When I run "osrm-contract --edge-weight-updates-over-factor 2 --segment-speed-file {speeds_file} {processed_file}"
```

A possible fix is to remove `And the data has been extracted` and add a new step like `And I route I should get` without extractAndContract call.

/cc @karenzshea

**Comment by karenzshea** [comment]
Thanks @oxidase ! I'm going to opt to just remove cache checks from this test. The test is focusing on the logged output from running `contract`, and in real use the user probably wouldn't be rerunning contraction on the originally extracted files anyway.
