### ISSUE TITLE
Logging Issues / Timeouts

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3232]
Recently, I've seen quite a lot of random fails on Travis. All of them seem to be connected to either timeouts or logging issues.

Every now and again, I see random tests fail due 5000ms timeouts.
Here is some output from a PR adding pure documentation:

```
1) Scenario: Bike - railway platforms - features/bicycle/area.feature:88
   Step: When I route I should get - features/bicycle/area.feature:101
   Step Definition: features/step_definitions/routing.js:4
   Message:
     function timed out after 5000 milliseconds

3) Scenario: Bike - Access tag trumphs barriers - features/bicycle/barrier.feature:24
   Step: Then routability should be - features/bicycle/barrier.feature:25
   Step Definition: features/step_definitions/routability.js:6
   Message:
     Error: socket hang up
         at createHangUpError (_http_client.js:213:15)
         at Socket.socketOnEnd (_http_client.js:305:23)
         at emitNone (events.js:72:20)
         at Socket.emit (events.js:166:7)
         at endReadableNT (_stream_readable.js:921:12)
         at nextTickCallbackWith2Args (node.js:442:9)
         at process._tickCallback (node.js:356:17)

4) Scenario: Bicycle - Use a ferry route - features/bicycle/bridge.feature:7
   Step: Before 
   Step Definition: features/support/hooks.js:31
   Message:
     Error: osrm-routed killed by signal SIGABRT: /home/travis/build/Project-OSRM/osrm-backend/build/osrm-routed --shared-memory=1 -p 5000
         at /home/travis/build/Project-OSRM/osrm-backend/features/lib/osrm_loader.js:119:23
         at ChildProcess.exithandler (child_process.js:220:5)
         at emitTwo (events.js:87:13)
         at ChildProcess.emit (events.js:172:7)
         at maybeClose (internal/child_process.js:829:16)
         at Socket.<anonymous> (internal/child_process.js:319:11)
         at emitOne (events.js:77:13)
         at Socket.emit (events.js:169:7)
         at Pipe._onclose (net.js:486:12)

6) Scenario: Bike - Cycle tracks/lanes should enable biking - features/bicycle/cycleway.feature:8
   Step: Then routability should be - features/bicycle/cycleway.feature:9
   Step Definition: features/step_definitions/routability.js:6
   Message:
     Error: *** osrm-datastore exited with 1: Error: Command failed: /home/travis/build/Project-OSRM/osrm-backend/build/osrm-datastore /home/travis/build/Project-OSRM/osrm-backend/test/cache/bicycle/cycleway.feature/63b18355f0899fdbd90042dc76bd45be/6fe40ee4e3a42b0126441b2fe6305683/8_bike_cycle_trackslanes_should_enable_biking.osrm
     [warn] A data update is in progress
         at /home/travis/build/Project-OSRM/osrm-backend/features/lib/osrm_loader.js:109:38
         at ChildProcess.exithandler (child_process.js:220:5)
         at emitTwo (events.js:87:13)
         at ChildProcess.emit (events.js:172:7)
         at maybeClose (internal/child_process.js:829:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

These errors seem to be more or less random. We should investigate what is going on here.

**Comment by daniel-j-h** [comment]
I haven't seen this in quite a while now. I think we also upped the Cucumber timeout at some point.

@MoKob want to close for now?

**Comment by MoKob** [comment]
I upped the timelimit for mac at one time. fine to close
