### ISSUE TITLE
cucumber error on Mac: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3672]
A cucumber test fails due to an error in the support code. It happens also in revision before my recent change to diff tables.

```
~/code/osrm-backend$ (master) git checkout 543f0e5e44611479e49175a5569d1fc0e86abc2f
Note: checking out '543f0e5e44611479e49175a5569d1fc0e86abc2f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 543f0e5... fix order of parameter initialisation for route parameters

~/code/osrm-backend$ ((543f0e5...)) node_modules/cucumber/bin/cucumber.js features/testbot/matching.feature:147
Node Version v5.7.1
@match @testbot
Feature: Basic Map Matching

  @match @testbot
  Scenario: Testbot - Duration details
  ✓ Given the profile "testbot"
  ✓ Given a grid size of 10 meters
  ✓ Given the extract extra arguments "--generate-edge-lookup"
  ✓ Given the query options
      | geometries | geojson |
  ✓ Given the query options
      | annotations | duration,nodes |
  ✓ Given the node map
      """
      a b c d e   g h
          i
      """
  ✓ And the ways
      | nodes   | oneway |
      | abcdegh | no     |
      | ci      | no     |
  ✓ And the speed file
      """
      1,2,36
      """
  ✓ And the contract extra arguments "--segment-speed-file {speeds_file}"
  ✖ When I match I should get
      | trace | matchings | a:duration      |
      | abeh  | abeh      | 1:0,1:1:1,0:2:1 |
      | abci  | abci      | 1:0,1,0:1       |
/Users/emil/code/osrm-backend/features/step_definitions/matching.js:147
                                outNode = subMatchings[si][ni];
                                                          ^

TypeError: Cannot read property '0' of undefined
    at testSubNode (/Users/emil/code/osrm-backend/features/step_definitions/matching.js:147:59)
    at headers.forEach.headers.forEach.testSubNode (/Users/emil/code/osrm-backend/features/step_definitions/matching.js:164:29)
    at /Users/emil/code/osrm-backend/features/step_definitions/matching.js:175:29
    at Array.forEach (native)
    at headers.forEach.headers.forEach.row.matchings.split.forEach (/Users/emil/code/osrm-backend/features/step_definitions/matching.js:174:50)
    at /Users/emil/code/osrm-backend/features/support/http.js:50:20
    at Object.<anonymous> (/Users/emil/code/osrm-backend/node_modules/node-timeout/lib/timeout.js:36:17)
    at Request._callback (/Users/emil/code/osrm-backend/features/support/http.js:39:24)
    at Request.self.callback (/Users/emil/code/osrm-backend/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
```

**Comment by daniel-j-h** [comment]
@emiltin can you test on recent master - I know @danpat and @MoKob regularly run the Cucumber tests on macOS. Also I see your node version is 5.7.1 - for the fun of it, can you try with v4 if you continue to see the issues on master?

**Comment by emiltin** [comment]
haven't seen this since
