### ISSUE TITLE
Pad-Left/Pad-Right require strings

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3716]
While rebasing onto master I ran into this failing test case:

```
1) Scenario: Weighting based on turn penalty file - features/car/traffic_turn_penalties.feature:73
   Step: When I route I should get - features/car/traffic_turn_penalties.feature:90
   Step Definition: features/step_definitions/routing.js:4
   Message:
     TypeError: actual[i][key].padRight is not a function
         at /Users/mokob/git/engine/project-osrm/osrm-backend/features/lib/table_diff.js:108:46
         at Array.forEach (native)
         at /Users/mokob/git/engine/project-osrm/osrm-backend/features/lib/table_diff.js:107:21
         at Array.forEach (native)
         at module.exports.expectedRows.forEach.headers.forEach.expectedRows.forEach.headers.forEach.expectedRows.forEach (/Users/mokob/git/engine/project-osrm/osrm-backend/features/lib/table_diff.js:79:18)
         at Queue._call (/Users/mokob/git/engine/project-osrm/osrm-backend/features/support/data.js:250:24)
         at maybeNotify (/Users/mokob/git/engine/project-osrm/osrm-backend/node_modules/d3-queue/build/d3-queue.js:109:34)
         at /Users/mokob/git/engine/project-osrm/osrm-backend/node_modules/d3-queue/build/d3-queue.js:85:14
         at headers.forEach.putValue (/Users/mokob/git/engine/project-osrm/osrm-backend/features/support/shared_steps.js:184:25)
         at /Users/mokob/git/engine/project-osrm/osrm-backend/features/support/http.js:50:20
```

It turns out that there was some difference in the tables. Since `padLeft/padRight` rely on strings,   they fail when we see numbers.

The problem can easily be fixed by explicitly casting to string, after which we see 

```
1) Scenario: Weighting based on turn penalty file - features/car/traffic_turn_penalties.feature:73
   Step: When I route I should get - features/car/traffic_turn_penalties.feature:90
   Step Definition: features/step_definitions/routing.js:4
   Message:
     Tables were not identical:
     | from | to |     route                | speed   | weight | time    |
     | a    | h  |     ad,dhk               | 65 km/h | 11     | 11s +-1 |
     | i    | g  |     fim,fg,fg            | 56 km/h | 12.8   | 12s +-1 |
     | a    | e  |     ad,def,def           | 67 km/h | 10.8   | 10s +-1 |
     | c    | g  |     cd,def,fg            | 65 km/h | 22     | 22s +-1 |
     | p    | g  |     mp,fim,fg,fg         | 61 km/h | 23.8   | 23s +-1 |
     | a    | l  |     ad,def,fim,klm,klm   | 58 km/h | 37     | 37s +-1 |
     | l    | e  |     klm,fim,def,def      | 44 km/h | 32.6   | 32s +-1 |
     | g    | n  |     fg,fim,mn,mn         | 28 km/h | 51.8   | 51s +-1 |
     | j    | c  | (-) jk,klm,fim,def,cd,cd | 53 km/h | 54.6   | 54s +-1 |
     | j    | c  | (+) jk,klm,fim,def,cd    | 53 km/h | 54.6   | 54s +-1 |
```

The code is affected [here](https://github.com/Project-OSRM/osrm-backend/blob/master/features/lib/table_diff.js#L71) and in a few following lines.

@emiltin can you have a look and see whether they can all be safely casted to strings?
(see https://github.com/Project-OSRM/osrm-backend/pull/3715)

**Comment by emiltin** [comment]
i think it's safe, since the affected code is only printing the output, and not involved in computing the diff.
