### ISSUE TITLE
Instructions to run Cucumber test locally doesn't work for me

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#3854]
Trying to follow the instructions at https://github.com/Project-OSRM/osrm-backend/wiki/Cucumber-Test-Suite#running-tests-locally on Ubuntu 16.04 fails for me.

I've installed nvm and node as described:

```shell
emil@emil-OptiPlex-7010:~/code/osrm-backend$ nvm run node --version
Running node v7.7.4 (npm v4.1.2)
v7.7.4
```
But running npm install fails:
```
emil@emil-OptiPlex-7010:~/code/osrm-backend$ npm install

> osrm@5.7.0 preinstall /home/emil/code/osrm-backend
> npm install node-pre-gyp

osrm@5.7.0 /home/emil/code/osrm-backend
└── node-pre-gyp@0.6.34 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> osrm@5.7.0 install /home/emil/code/osrm-backend
> node-pre-gyp install --fallback-to-build=false

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.7.0/Release/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/emil/code/osrm-backend/node_modules/node-pre-gyp/lib/install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:191:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/emil/code/osrm-backend/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-66-generic
node-pre-gyp ERR! command "/home/emil/.nvm/versions/node/v7.7.4/bin/node" "/home/emil/code/osrm-backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/emil/code/osrm-backend
node-pre-gyp ERR! node -v v7.7.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.7.0/Release/node-v51-linux-x64.tar.gz

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/home/emil/.nvm/versions/node/v7.7.4/bin/node" "/home/emil/.nvm/versions/node/v7.7.4/bin/npm" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! osrm@5.7.0 install: `node-pre-gyp install --fallback-to-build=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osrm@5.7.0 install script 'node-pre-gyp install --fallback-to-build=false'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/emil/code/osrm-backend/npm-debug.log
```
Looks like a problem with downloading https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.7.0/Release/node-v51-linux-x64.tar.gz?

**Comment by TheMarex** [comment]
@emiltin urg sorry about that. Two options here:

1/ Build with `ENABLE_NODE_BINDINGS=On`
2/ Run with `npm install --ignore-scripts`

The npm setup needs some fine tuning after we merged the node bindings in here recently.

**Comment by emiltin** [comment]
thanks, npm install --ignore-scripts worked.

**Comment by emiltin** [comment]
note: if you already have the ruby version of cucumber linked, then you you will need to unlink that and link the js version, or use node_modules/cucumber/bin/cucumber.js.

**Comment by TheMarex** [comment]
Fixed by fallback script. `npm install ` should just work now.
