### ISSUE TITLE
Documentation build is broken due

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4043]
Building our documentation currently fails with:

```
  43 | 

  44 | export default class App extends React.PureComponent {

> 45 |   static propTypes = {

     |   ^

  46 |     content: PropTypes.string.isRequired,

  47 |     ast: PropTypes.object.isRequired

  48 |   }

    at File.buildCodeFrameError (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-core/lib/transformation/file/index.js:427:15)

    at NodePath.buildCodeFrameError (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-traverse/lib/path/index.js:140:26)

    at pushBody (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:262:20)

    at buildBody (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:229:10)

    at run (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:143:10)

    at PluginPass.ClassExpression (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:48:60)

    at newFn (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-traverse/lib/visitors.js:276:21)

    at NodePath._call (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-traverse/lib/path/context.js:76:18)

    at NodePath.call (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-traverse/lib/path/context.js:48:17)

    at NodePath.visit (/home/travis/build/Project-OSRM/osrm-backend/node_modules/babel-traverse/lib/path/context.js:105:12)

SyntaxError: src/components/app.js: Missing class properties transform.

  43 | 

  44 | export default class App extends React.PureComponent {

> 45 |   static propTypes = {

     |   ^

  46 |     content: PropTypes.string.isRequired,

  47 |     ast: PropTypes.object.isRequired

  48 |   }
```

This looks like a silent dependency upgrade somewhere in the tree.

**Comment by daniel-j-h** [comment]
Got resolved in https://github.com/Project-OSRM/osrm-backend/pull/4041

**Comment by daniel-j-h** [comment]
Reopening here. We're hitting the same issue again now on the 5.8 branch. Upgrading to `4.0.0-beta.18` does not help. This is blocking bumping http://project-osrm.org/docs/v5.7.0/api/ to 5.8.

**Comment by daniel-j-h** [comment]
👋 @tmcw any ideas on the `documentation.js`-internal error we're hitting here? I think @TheMarex or @danpat did [the integration](https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/build_api_docs.sh#L17) but I'm not sure if we're doing something wrong here. This looks like a React usage-issue to me.

**Comment by tmcw** [comment]
The linked line & the reported bug don't match: https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/build_api_docs.sh#L17 is documenting a cpp file, the OP is produced by documenting a JavaScript file that I don't see referenced in this issue.

**Comment by tmcw** [comment]
Additionally, http://project-osrm.org/docs/v5.7.0/api/ is a docbox documentation site, not a documentation.js one. I think there are some wires crossed here.

**Comment by TheMarex** [comment]
Ah sorry I should have specified which documentation throws an error for me:

[This](https://github.com/Project-OSRM/osrm-backend/blob/09df8d47a532ffba7b4b53fe5a61eb4971e2f906/scripts/build_api_docs.sh#L19-L44) is the code @danpat wrote to setup our docbox instance.

Currently I'm seeing the following error message locally:

```
SyntaxError: /home/patrick/Code/osrm-temp/build/docs/tmp/src/components/app.js: Missing class properties transform.
  43 | 
  44 | export default class App extends React.PureComponent {
> 45 |   static propTypes = {
     |   ^
  46 |     content: PropTypes.string.isRequired,
  47 |     ast: PropTypes.object.isRequired
  48 |   }
    at File.buildCodeFrameError (/home/patrick/Code/osrm-temp/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at NodePath.buildCodeFrameError (/home/patrick/Code/osrm-temp/node_modules/babel-traverse/lib/path/index.js:140:26)
    at pushBody (/home/patrick/Code/osrm-temp/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:262:20)
    at buildBody (/home/patrick/Code/osrm-temp/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:229:10)
    at run (/home/patrick/Code/osrm-temp/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:143:10)
    at PluginPass.ClassExpression (/home/patrick/Code/osrm-temp/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:48:60)
    at newFn (/home/patrick/Code/osrm-temp/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/patrick/Code/osrm-temp/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/patrick/Code/osrm-temp/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/patrick/Code/osrm-temp/node_modules/babel-traverse/lib/path/context.js:105:12)
SyntaxError: src/components/app.js: Missing class properties transform.
  43 | 
  44 | export default class App extends React.PureComponent {
> 45 |   static propTypes = {
     |   ^
  46 |     content: PropTypes.string.isRequired,
  47 |     ast: PropTypes.object.isRequired
  48 |   }
```

This can be reproduced by running `yarn && yarn docs` on `master`.

**Comment by tmcw** [comment]
Debugging custom build scripts is a bit outside of my domain here: [docbox comes with scripts in its npm package](https://github.com/tmcw/docbox/blob/master/package.json#L6) that are guaranteed to work, and any other kind of setup is out of scope for the project. It looks like this custom setup isn't [correctly using a .babelrc](https://github.com/tmcw/docbox/blob/master/.babelrc) or installing the necessary transforms, as is indicated in the error message.
