### ISSUE TITLE
npm install fails with access denied for mapbox-node-binary.s3.amazonaws.com packages

### ISSUE THREAD

**Issue by mloskot** [Project-OSRM/osrm-backend#4228]
I'm following [Cucumber Test Suite](https://github.com/Project-OSRM/osrm-backend/wiki/Cucumber-Test-Suite) to run the master branch tests on [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about):

I have the Node installed
```
$ node --version
v8.1.3
$ npm --version
5.0.3
```

and during install of the Node dependencies from `package.json`, I'm getting this
```
$ cd /mnt/d/dev/osrm-backend
$ npm install

> osrm@5.8.0-latest.1 install /mnt/d/dev/osrm-backend
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.8.0-latest.1/Release/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/mnt/d/dev/osrm-backend/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:120:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/mnt/d/dev/osrm-backend/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! System Linux 4.4.0-43-Microsoft
node-pre-gyp ERR! command "/usr/bin/nodejs" "/mnt/d/dev/osrm-backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /mnt/d/dev/osrm-backend
node-pre-gyp ERR! node -v v8.1.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.8.0-latest.1/Release/node-v57-linux-x64.tar.gz
./scripts/node_install.sh: line 2: $'\r': command not found
: invalid optionnstall.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./scripts/node_install.sh: line 4: $'\r': command not found
./scripts/node_install.sh: line 6: $'\r': command not found
./scripts/node_install.sh: line 21: syntax error: unexpected end of file
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! osrm@5.8.0-latest.1 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the osrm@5.8.0-latest.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mloskot/.npm/_logs/2017-07-03T13_52_47_009Z-debug.log
```

Is this expected to get Access Denied for https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.8.0-latest.1/Release/node-v57-linux-x64.tar.gz ?

------

`npm install --ignore-script` mentioned in https://github.com/Project-OSRM/osrm-backend/issues/4216#issuecomment-312232034 seems to work around the problem.

**Comment by daniel-j-h** [comment]
We only build binaries for Node.js LTS versions 4 and 6 at the moment.

```
./scripts/node_install.sh: line 2: $'\r': command not found
: invalid optionnstall.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./scripts/node_install.sh: line 4: $'\r': command not found
./scripts/node_install.sh: line 6: $'\r': command not found
./scripts/node_install.sh: line 21: syntax error: unexpected end of file
```

coming from https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/node_install.sh seems to be either a Bash-on-Windows issue - or do we have to set the shebang to `#!/usr/bin/env bash` (?).

**Comment by mloskot** [comment]
@daniel-j-h `dos2unix`-ing the `node_install.sh` fixes the problem.

`git clone` run on Windows does `core.autocrlf=true` by default and `.sh` scripts are infected with `CRLF`. I've proposed #4235 to work around such problems.
