### ISSUE TITLE
make -C test/data: no such file or directory, open 'monaco.osm.pbf

### ISSUE THREAD

**Issue by mloskot** [Project-OSRM/osrm-backend#4229]
I'm following [Cucumber Test Suite](https://github.com/Project-OSRM/osrm-backend/wiki/Cucumber-Test-Suite) to run the master branch tests on [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about):

I have the Node installed
```
$ node --version
v8.1.3
$ npm --version
5.0.3
```

The `make -C test/data` step is failing:

```
$ cd /mnt/d/dev/osrm-backend/test/data
$ make
wget https://s3.amazonaws.com/mapbox/osrm/testing/monaco.osm.pbf -O monaco.osm.pbf
--2017-07-03 16:15:43--  https://s3.amazonaws.com/mapbox/osrm/testing/monaco.osm.pbf
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.18.195
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.18.195|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1759101 (1.7M) [binary/octet-stream]
Saving to: ‘monaco.osm.pbf’

100%[=====================================>]  1,759,101    211KB/s   in 8.6s

2017-07-03 16:16:00 (200 KB/s) - ‘monaco.osm.pbf’ saved [1759101/1759101]

wget https://s3.amazonaws.com/mapbox/osrm/testing/monaco.poly -O monaco.poly
--2017-07-03 16:16:00--  https://s3.amazonaws.com/mapbox/osrm/testing/monaco.poly
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.48.147
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.48.147|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 852 [binary/octet-stream]
Saving to: ‘monaco.poly’

100%[=====================================>]  852         --.-K/s   in 0s

2017-07-03 16:16:06 (14.3 MB/s) - ‘monaco.poly’ saved [852/852]

Verifiyng data file integrity...
../../scripts/md5sum.js -c data.md5sum
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

'rror: ENOENT: no such file or directory, open 'monaco.osm.pbf
    at Object.fs.openSync (fs.js:651:18)
    at md5FileSync (/mnt/d/dev/osrm-backend/scripts/md5sum.js:30:15)
    at /mnt/d/dev/osrm-backend/scripts/md5sum.js:72:24
    at Array.forEach (native)
    at validate (/mnt/d/dev/osrm-backend/scripts/md5sum.js:67:9)
    at Object.<anonymous> (/mnt/d/dev/osrm-backend/scripts/md5sum.js:15:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
make: *** [monaco.osrm] Error 1
```

AFAICT, `monaco.osm.pbf`  as well as `data.md5sum` are in place:
```
$ cd /mnt/d/dev/osrm-backend/test/data
$ ls
data.md5sum  Makefile  monaco.osm.pbf  monaco.poly  stxxl.errlog  stxxl.log  tz
```

I'm not very experienced with NodeJS, but is there an incompatibility with Node v8 possible?
Should I re-install Node v4?  This seems somewhat related #4216

------

If I comment line `test/data/Makefile:45` with `$(MD5SUM)` invocation:
```
$(DATA_NAME).osrm: $(DATA_NAME).osm.pbf $(DATA_NAME).poly $(PROFILE) $(OSRM_EXTRACT)
	@echo "Verifiyng data file integrity..."
	#$(MD5SUM) -c data.md5sum
        ....
```
then `make` completes building data with success:

```
$ make
Verifiyng data file integrity...
#../../scripts/md5sum.js -c data.md5sum
Running osrm-extract...
../../scripts/timer.js "osrm-extract\tmonaco.osrm" ../../build/osrm-extract monaco.osm.pbf -p ../../profiles/car.lua
mkdir -p ch
cp monaco.osrm monaco.osrm.* ch/
Running osrm-contract...
../../scripts/timer.js "osrm-contract\tch/monaco.osrm.hsgr" ../../build/osrm-contract ch/monaco.osrm
mkdir -p corech
cp monaco.osrm monaco.osrm.* corech/
Running osrm-contract...
../../scripts/timer.js "osrm-contract\tcorech/monaco.osrm.hsgr" ../../build/osrm-contract --core=0.5 corech/monaco.osrm
mkdir -p mld
cp monaco.osrm monaco.osrm.* mld/
Running osrm-partition...
../../scripts/timer.js "osrm-partition\tmld/monaco.osrm.partition" ../../build/osrm-partition mld/monaco.osrm
../../scripts/timer.js "osrm-customize\tmld/monaco.osrm.partition" ../../build/osrm-customize mld/monaco.osrm
```

**Comment by daniel-j-h** [comment]
I'm not sure why you're seeing the error while trying to open the file - what I am sure of is that we bundle only pre-built binaries for Node.js LTS versions 4 and 6 and only on Linux and macOS.

    npm install --ignore-scripts
    npm install --build-from-source

But running the data tests does not require Node.js at all.

I guess the md5sum Js script has some issues with Node.js version 8. Not sure why we're using a script there anyway the `md5sum` binary should work just as well.

**Comment by mloskot** [comment]
TL;TR: There must be a bug in Bash on Windows

Replacing the JS script with `md5sum` command does not help here as it can not find the present data files either.

Plain Ubuntu 16.04:
```
$ ls
data.md5sum  Makefile  monaco.osm.pbf  monaco.poly  tz
$ md5sum -c data.md5sum 
monaco.osm.pbf: OK
monaco.poly: OK
```

* Bash on Windows
```
$ ls monaco.osm.pbf monaco.poly data.md5sum                                                                                                                    data.md5sum  monaco.osm.pbf  monaco.poly                                                                                                                                                                       mloskot@DEV604:/mnt/d/dev/osrm-backend/test/data$ md5sum -c data.md5sum                                                                                                                                        : No such file or directory                                                                                                                                                                                    : FAILED open or read                                                                                                                                                                                          : No such file or directory                                                                                                                                                                                    : FAILED open or read                                                                                                                                                                                          md5sum: WARNING: 2 listed files could not be read       
```

Since there us clearly something fishy going on on Bash On Windows/WSL, I think this issue can be closed.

**Comment by daniel-j-h** [comment]
Yep I'm fine with closing here as it's tracked upstream already.
