### ISSUE TITLE
node-osrm install fails on macOS with NodeJS 8.5.0

### ISSUE THREAD

**Issue by stepankuzmin** [Project-OSRM/osrm-backend#4546]
Can't install OSRM (5.11.0, 5.12.0, 5.13.0-cardinal.1) on macOS Sierra with NodeJS v8.5.0

```sh
npm i osrm@5.12.0

> osrm@5.12.0 install /Users/stepan/projects/node-isochrone/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.12.0/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/stepan/projects/node-isochrone/node_modules/osrm/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:120:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/stepan/projects/node-isochrone/node_modules/osrm/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:454:20)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/stepan/.nvm/versions/node/v8.5.0/bin/node" "/Users/stepan/projects/node-isochrone/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/stepan/projects/node-isochrone/node_modules/osrm
node-pre-gyp ERR! node -v v8.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.12.0/Release/node-v57-darwin-x64.tar.gz
~/projects/node-isochrone/node_modules/osrm/build ~/projects/node-isochrone/node_modules/osrm
CMake Error: The source directory "/Users/stepan/projects/node-isochrone/node_modules/osrm" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osrm@5.12.0 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osrm@5.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stepan/.npm/_logs/2017-09-26T09_35_15_091Z-debug.log
```

It seems that there is some problem with permissions, according to 

```
Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.12.0/Release/node-v57-darwin-x64.tar.gz
```

**Comment by quiqua** [comment]
The Node.js bindings are only available for Node.js 4 and 6 (https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml provide you with that information)

If you use any other version, try this:

```
npm install --build-from-source
```
https://github.com/Project-OSRM/osrm-backend#using-the-nodejs-bindings

**Comment by stepankuzmin** [comment]
Thanks for the reply! Are there any plans for adding Node v8 support? Or is there any way to add this?

**Comment by daniel-j-h** [comment]
We could add Node v8 builds to our Travis CI config. for Linux and macOS. The problem with that is it will add even more builds (`{Linux, macOS} x {Debug, Release}`) to our large list of CI builds we need to wait for: https://travis-ci.org/Project-OSRM/osrm-backend/

So we're trying to put it off as long as possible but we might need to do that at some point.

Starting with Node v8 I would love to compile the Node.js bindings against the new N-API (see 
https://github.com/Project-OSRM/osrm-backend/issues/4118). Then we can build a single binding artifact and all future Node.js versions can make use of it.
