### ISSUE TITLE
npm install osrm -- not working (missing files)

### ISSUE THREAD

**Issue by CraigglesO** [Project-OSRM/osrm-backend#4679]
```
Directory: /Users/craigoconnor/Desktop/galton-master/node_modules/osrm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@8.1.2 | darwin | x64
node-pre-gyp info check checked for "/Users/craigoconnor/Desktop/galton-master/node_modules/osrm/lib/binding/node_osrm.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.10.0/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.10.0/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.10.0/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/craigoconnor/Desktop/galton-master/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:120:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/craigoconnor/Desktop/galton-master/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! System Darwin 17.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/craigoconnor/Desktop/galton-master/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/craigoconnor/Desktop/galton-master/node_modules/osrm
node-pre-gyp ERR! node -v v8.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.10.0/Release/node-v57-darwin-x64.tar.gz
```

Am I writing in the wrong section? Any suggestions to move forward?

**Comment by danpat** [comment]
@CraigglesO hmm, not sure why GDAL would've fixed this - the problem is that we haven't published a Node 8.x module for OSRM 5.10.

There should be Node 8 binaries for OSRM 5.14 and onwards, but that's the next release, and nothing has been uploaded yet.

Downgrade to Node 6 or 4 and things should work fine.
