### ISSUE TITLE
npm Install osrm fails

### ISSUE THREAD

**Issue by cm4ker** [Project-OSRM/osrm-backend#4841]
Hi! I have the issue with installing osrm from npm.

OS: Windows 10 (x64)
Node.js versions I had tried: 8.9.4, 6.12.3, 6.11.0, 6.0.0, 4.7.0, 4.6.2

Firstly I install node.js version 8.9.4
And just run: `npm install osrm`. I get the same error #4675.

Then I install nvm and install node.js version 6.0.0 and run `npm install osrm`

I had this messages:

```
C:\Users\myuser\galton\galton>nvm use 6
6.0.0
Now using node v6.0.0 (64-bit)

C:\Users\myuser\galton\galton>npm install

> osrm@5.15.1 install C:\Users\myuser\galton\galton\node_modules\osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.15.1/Release/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\myuser\galton\galton\node_modules\osrm\node_modules\node-pre-gyp\lib\install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\myuser\galton\galton\node_modules\osrm\node_modules\request\request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:359:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myuser\\galton\\galton\\node_modules\\osrm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\myuser\galton\galton\node_modules\osrm
node-pre-gyp ERR! node -v v6.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.15.1/Release/node-v48-win32-x64.tar.gz
"." не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osrm@5.15.1 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.15.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2018-02-01T08_11_01_408Z-debug.log
```

Can you help me, what I am doing wrong?

**Comment by TheMarex** [comment]
Sorry we don't support node binaries on Windows right now. 😞  If you can figure out how to compile it, let me know!

**Comment by cm4ker** [comment]
Hi, @TheMarex. This will be cool if you help me. I will write the instruction for build osrm for Windows then. I'm the beginner in node. How I can contact with you?

**Comment by TheMarex** [comment]
@cm4ker we typically use `osrm-talk@openstreetmap.org`

**Comment by tyjoti89** [comment]
@cm4ker Any progress on this? I would really like to get an OSRM server running in any way shape or form, running on Windows. Node Express is the first solution that comes to mind, but I'm running into that 403 as well.

**Comment by cm4ker** [comment]
@tyjoti89 Hi! Nope I up it in docker instead.
