### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go

### ISSUE THREAD

**Issue by fungus1487** [Project-OSRM/osrm-backend#4862]
Getting the following where running

`sudo docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/spain-latest.osm.pbf`

Any ideas?

```
sudo docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/spain-latest.osm.pbf
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"read init-p: connection reset by peer\"": unknown.
ubuntu@ip-172-31-9-79:~$ sudo docker run -t -v $(pwd):/data osrm/osrm-backend osrm-contract /data/spain-latest.osrm
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d745f54cb0294e6369494abcd1f2c4c1a49b4bebf9ae9371a9918779503f18a5/log.json: no such file or directory): docker-runc did not terminate sucessfully: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f4b5c3f5428 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:298 fp=0xc420024780 sp=0xc420024778 pc=0x565047b2acb0
runtime.main()
        /usr/local/go/src/runtime/proc.go:128 +0x67 fp=0xc4200247e0 sp=0xc420024780 pc=0x565047b00297
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200247e8 sp=0xc4200247e0 pc=0x565047b2d8f1

rax    0x0
rbx    0x7f4b5c785700
rcx    0x7f4b5c3f5428
rdx    0x6
rdi    0xeef
rsi    0xeef
rbp    0x565047e02a4e
rsp    0x7ffcf0140bb8
r8     0x7f4b5c786770
r9     0x7f4b5d21b700
r10    0x8
r11    0x202
r12    0x56504a130050
r13    0xf1
r14    0x11
r15    0x0
rip    0x7f4b5c3f5428
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
: unknown.
```

**Comment by fungus1487** [comment]
The installation is pretty standard and has worked fine with gb, german, netherlands data sets.

It's worth noting I am running 3 other instances of the docker image which serve gb, german, netherlands on different ports. When I came to do the 4th (spain) I get the above error.

**Comment by danpat** [comment]
Hmm, there isn't much to go on with these messages, but this smells a bit like resource limits (memory, storage, ???) inside the container, and isn't OSRM specific.

Do you have access to the docker daemon logs to see if there is anything more useful there?

The first error message: `read init-p: connection reset by peer` has a few google hits, and most of them look like Docker or kernel bugs - not OSRM specific.

**Comment by fungus1487** [comment]
It was resource starvation in the end, changed the AWS instance from m4.large (2vcpu 4GB RAM) to M4.xlarge (4vcpu 8GB RAM) and all is well.
