### ISSUE TITLE
npm error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.16.2/Release/node-v59-win32-x64.tar.gz

### ISSUE THREAD

**Issue by ifle** [Project-OSRM/osrm-backend#4940]
I have this error when I do npm i osrm on Windows

```
PS D:\Dev\OSRM\web\osrm-web> npm i osrm -save

> osrm@5.16.2 install D:\Dev\OSRM\web\osrm-web\node_modules\osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.16.2/Release/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (D:\Dev\OSRM\web\osrm-web\node_modules\osrm\node_modules\node-pre-gyp\lib\install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:132:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (D:\Dev\OSRM\web\osrm-web\node_modules\osrm\node_modules\request\request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:127:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:444:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:127:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:269:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:256:11)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Dev\\OSRM\\web\\osrm-web\\node_modules\\osrm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd D:\Dev\OSRM\web\osrm-web\node_modules\osrm
node-pre-gyp ERR! node -v v9.7.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.16.2/Release/node-v59-win32-x64.tar.gz
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osrm@5.16.2 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.16.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by danpat** [comment]
We do not yet support NodeJS 9.x, please downgrade to 8.x LTS.

**Comment by TheMarex** [comment]
> I'm not sure if we're publishing nodeJS modules for Windows at all tbh....

No we don't. :see_no_evil: Sorry!

**Comment by ajinkyaghorpade** [comment]
> We do not yet support NodeJS 9.x, please downgrade to 8.x LTS.
> 
> I'm not sure if we're publishing nodeJS modules for Windows at all tbh....

It would be very helpful if this requirement is updated in the read.me file for the project in github here - https://github.com/Project-OSRM/osrm-backend#using-the-nodejs-bindings

Thanks in advance!
