### ISSUE TITLE
installing node module osrm in docker image

### ISSUE THREAD

**Issue by Grigsuv** [Project-OSRM/osrm-backend#5080]
Hi,I need to build docker image of node/osrm project
Dockerfile
```
FROM node:6.11.5 #also treid 6 and 6.11
ENV worker null
WORKDIR /app
COPY package.json /app
RUN npm install
RUN npm install osrm@5.6.5
COPY . /app
CMD ["sh", "-c", "node index.js --worker=${worker}"]
```

`dockerignore`
`node_modules`
getting this
```
Step 6/8 : RUN npm install osrm@5.6.5
 ---> Running in e0b43233ea75
npm WARN lifecycle osrm@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) osrm@5.6.5 npm install node-pre-gyp /app/node_modules/.staging/osrm-8ed85afe`
```

after all build ends with no error but can't run image,throwing this error
```
$ docker run -t -e worker=5 osrm
module.js:597`
  return process.dlopen(module, path._makeLong(filename));
                 ^

`Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /app/node_modules/osrm/lib/binding/node-osrm.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/osrm/lib/index.js:1:91)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Is there any ways to solve this problem?

**Comment by Grigsuv** [comment]
@danpat So there are no way to install version 5.6.5?

**Comment by danpat** [comment]
@Grigsuv There is always a way, it's just not easy.

The way to do it would be to build your own modules from the `5.6.5` git tag, and backport my fixes from https://github.com/Project-OSRM/osrm-backend/commit/7d9b17fd41f0c7c70b42afced73c4a73f9d0ff0e.

Given how much OSRM has improved since 5.6.5, it's not something I would personally spend much time on - I'd upgrade to a newer version and save myself some heartache.
