### ISSUE TITLE
Building Node bindings from source: "gyp: binding.gyp not found"

### ISSUE THREAD

**Issue by datwelk** [Project-OSRM/osrm-backend#5776]
I am trying to build the Node.js bindings from source. My Dockerfile looks as follows:

```
# This will build a Docker container with a node js server
# inside.
# We pick Debian Stretch, same as original osrm Docker build script.
FROM node:10-stretch-slim AS builder

RUN mkdir -p /src
COPY . /src
WORKDIR /src

# Install required packages for building
# OSRM from source, then install the node.js
# bindings.
RUN apt-get update && \
    apt-get -y --no-install-recommends install cmake make git gcc g++ libbz2-dev libxml2-dev \
    libzip-dev libboost1.62-all-dev lua5.2 liblua5.2-dev libtbb-dev -o APT::Install-Suggests=0 -o APT::Install-Recommends=0 && \
    npm install --ignore-scripts --unsafe-perm && \
    mkdir -p build && \
    cd build && \
    BUILD_TYPE="Release" && \
    ENABLE_ASSERTIONS="Off" && \
    BUILD_TOOLS="Off" && \
    cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_ASSERTIONS=${ENABLE_ASSERTIONS} -DBUILD_TOOLS=${BUILD_TOOLS} -DENABLE_LTO=On -DENABLE_NODE_BINDINGS=ON && \
    make -j${NPROC} install && \
    cd /src && \
    npm install --build-from-source --unsafe-perm

# Copy the files from .npmignore
# The OSRM bindings are installed to node_modules now inside
# the builder. Copy the entire dir to the runner.
FROM node:10-stretch AS runner
RUN mkdir -p /src
COPY --from=builder /src/node/ /src/
COPY --from=builder /src/taginfo.json /src/taginfo.json
COPY --from=builder /src/lib/ /src/lib/
COPY --from=builder /src/profiles/ /src/profiles/
COPY --from=builder /src/scripts/node_install.sh /src/scripts/node_install.sh
COPY --from=builder /src/node_modules/ /src/node_modules/
WORKDIR /src

RUN npm install

EXPOSE 5000

# To use: provide the OSRM_GRAPH as environment variable!
CMD ["npm", "run start"]
```

All steps succeed until the `npm install --build-from-source --unsafe-perm` command. This is the error I get:

```
node-pre-gyp install --fallback-to-build=true || ./scripts/node_install.sh
node-pre-gyp WARN Using request for node-pre-gyp https download
gyp: binding.gyp not found (cwd: /src) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: 'gyp' failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build=true" "--module=/src/lib/binding/node_osrm.node" "--module_name=node_osrm" "--module_path=/src/lib/binding" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /src
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build=true --module=/src/lib/binding/node_osrm.node --module_name=node_osrm --module_path=/src/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/src/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.76-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=true"
node-pre-gyp ERR! cwd /src
node-pre-gyp ERR! node -v v10.21.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build=true --module=/src/lib/binding/node_osrm.node --module_name=node_osrm --module_path=/src/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
Detected existing build directory, skipping compiling.
```

Am I missing something regarding a "binding.gyp" file? Or is it not supposed to look for this file at all?

**Comment by danpat** [comment]
Your `COPYFROM` lines are missing the `/src/binding.gyp` file.

**Comment by datwelk** [comment]
Both `COPY /src/binding.gyp /src/binding.gyp` `COPY /src/src/binding.gyp /src/binding.gyp` don't fix it. Is the `binding.gyp` file created as part of building the Node.js bindings? Because it's not present in the repository itself.

**Comment by datwelk** [comment]
Got it to work by directly accessing the produced bindings in `lib/binding/node_osrm.node`. I guess the `binding.gyp` stuff is mostly relevant for packaging and publishing.

**Comment by wangyoucao577** [comment]
I met same problem. However, I didn't find the `/src/binding.gyp` on the latest `master` https://github.com/Project-OSRM/osrm-backend/tree/master/src. Any idea?

**Comment by wangyoucao577** [comment]
I have tried to find `binding.gyp` from history but failed. It seems that the file never exist. Then I tried  `./scripts/node_install.sh` and it works for me.

**Comment by antoine-giret** [comment]
> I have tried to find `binding.gyp` from history but failed. It seems that the file never exist, so I guess the `npm install --build-from-source` may never works. @danpat Please correct me if I'm wrong. Thanks!
> 
> Then I tried `./scripts/node_install.sh` and it works for me.

Hi ! Any Up ?
