### ISSUE TITLE
npm run docs failed

### ISSUE THREAD

**Issue by wangyoucao577** [Project-OSRM/osrm-backend#5867]
- Env      
Debian stretch
```bash
[root]$ node --version
v10.22.1
[root]$ npm --version
6.14.6
```

nodejs bindings has been built succeed via `./scripts/node_install.sh`.         

- Install babel
```bash
[root]$ npm install --save-dev @babel/core @babel/cli
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@nicolo-ribaudo/chokidar-2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/@babel/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @babel/cli@7.12.1
+ @babel/core@7.12.3
removed 12 packages, updated 2 packages and audited 1499 packages in 15.145s

1 package is looking for funding
  run `npm fund` for details

found 1167 vulnerabilities (612 low, 15 moderate, 539 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

- build docs
```bash
[root]$ npm run docs

> osrm@5.23.0 docs /workspace/osrm-backend
> ./scripts/build_api_docs.sh

/workspace/osrm-backend/build/docs/tmp /workspace/osrm-backend
... 
WARN: Output exceeds 32000 characters
Error: Plugin/Preset files are not allowed to export objects, only functions. In /workspace/osrm-backend/node_modules/babel-preset-stage-0/lib/index.js
    at createDescriptor (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-chain.js:416:26)
    at /workspace/osrm-backend/node_modules/@babel/core/lib/config/config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (/workspace/osrm-backend/node_modules/@babel/core/lib/config/config-chain.js:228:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osrm@5.23.0 docs: `./scripts/build_api_docs.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.23.0 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T10_04_55_201Z-debug.log
```

- detailed error log 
```bash
[root]$ cat /root/.npm/_logs/2020-10-22T10_04_55_201Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v10.22.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v10.22.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'docs' ]
2 info using npm@6.14.6
3 info using node@v10.22.1
4 verbose run-script [ 'predocs', 'docs', 'postdocs' ]
5 info lifecycle osrm@5.23.0~predocs: osrm@5.23.0
6 info lifecycle osrm@5.23.0~docs: osrm@5.23.0
7 verbose lifecycle osrm@5.23.0~docs: unsafe-perm in lifecycle true
8 verbose lifecycle osrm@5.23.0~docs: PATH: /root/.nvm/versions/node/v10.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/workspace/osrm-backend/node_modules/.bin:/root/.nvm/versions/node/v10.22.1/bin:/workspace/osmium/bin:/workspace/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle osrm@5.23.0~docs: CWD: /workspace/osrm-backend
10 silly lifecycle osrm@5.23.0~docs: Args: [ '-c', './scripts/build_api_docs.sh' ]
11 silly lifecycle osrm@5.23.0~docs: Returned: code: 1  signal: null
12 info lifecycle osrm@5.23.0~docs: Failed to exec docs script
13 verbose stack Error: osrm@5.23.0 docs: `./scripts/build_api_docs.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid osrm@5.23.0
15 verbose cwd /workspace/osrm-backend
16 verbose Linux 3.10.0-1062.9.1.el7.x86_64
17 verbose argv "/root/.nvm/versions/node/v10.22.1/bin/node" "/root/.nvm/versions/node/v10.22.1/bin/npm" "run" "docs"
18 verbose node v10.22.1
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error osrm@5.23.0 docs: `./scripts/build_api_docs.sh`
22 error Exit status 1
23 error Failed at the osrm@5.23.0 docs script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any idea?

**Comment by mjjbell** [comment]
I was able to generate the docs by downgrading `babel-cli` to v6 and `documentation` to v4.

I expect some work is required to support latest versions of these libraries.
E.g. `documentation` no longer has a `--polyglot` [option](https://github.com/documentationjs/documentation/blob/master/docs/USAGE.md) used by the [build script](https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/build_api_docs.sh#L17) to autogenerate NodeJS docs.
