### ISSUE TITLE
macOS Ventura does not support the OSRM node.

### ISSUE THREAD

**Issue by KaSakee** [Project-OSRM/osrm-backend#6430]
Unfortunately, I upgraded to macOS Ventura, attempted to run my backend, and received this OSRM error.

```
node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/binding/node_osrm.node, 0x0001): tried: '/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/binding/node_osrm.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/binding/node_osrm.node' (no such file), '/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/binding/node_osrm.node' (not a mach-o file)
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/index.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.12.0
```

Do you have any idea what's going on?

**Comment by KaSakee** [comment]
Even npm i --save OSRM gives an error,


```
npm ERR! code 1
npm ERR! path /Users/mac/Desktop/backends/backend/node_modules/osrm
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
npm ERR! response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz
npm ERR! ~/Desktop/backends/backend/node_modules/osrm/build ~/Desktop/backends/backend/node_modules/osrm
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.12.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/binding/node_osrm.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /Users/mac/Desktop/backends/backend/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mac/Desktop/backends/backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /Users/mac/Desktop/backends/backend/node_modules/osrm
npm ERR! node-pre-gyp ERR! node -v v18.12.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! CMake Warning:
npm ERR!   Ignoring extra path from command line:
npm ERR! 
npm ERR!    ".."
npm ERR! 
npm ERR! 
npm ERR! CMake Error: The source directory "/Users/mac/Desktop/backends/backend/node_modules/osrm" does not appear to contain CMakeLists.txt.
npm ERR! Specify --help for usage, or press the help button on the CMake GUI.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2022-10-30T02_00_52_193Z-debug-0.log
```

**Comment by SiarheiFedartsou** [comment]
Are you using Apple Silicon Mac? It looks like it tries to download arm64 binary of 5.26.0 which does not exist. Can you try 5.27.0?

**Comment by KaSakee** [comment]
> Are you using Apple Silicon Mac? It looks like it tries to download arm64 binary for 5.26.0 which does not exist. Can you try 5.27.0?

I'm using M1 Macbook Pro yes.

**Comment by SiarheiFedartsou** [comment]
We moved to another NPM repo recently, try smth like `npm install @project-osrm/osrm`

**Comment by KaSakee** [comment]
I tested the updated repository. The same problem occurs with the newest version.

`npm install @project-osrm/osrm@5.27.1` --save or `npm install @project-osrm/osrm--save`

On `macOS Ventura`



Error:

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/mac/Desktop/backends/backend/node_modules/@project-osrm/osrm
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
npm ERR! response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.27.1/node_osrm-v5.27.1-node-v111-darwin-arm64-Release.tar.gz
npm ERR! ~/Desktop/backends/backend/node_modules/@project-osrm/osrm/build ~/Desktop/backends/backend/node_modules/@project-osrm/osrm
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@19.0.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/mac/Desktop/backends/backend/node_modules/@project-osrm/osrm/lib/binding/node_osrm.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Project-OSRM/osrm-backend/releases/download/v5.27.1/node_osrm-v5.27.1-node-v111-darwin-arm64-Release.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.27.1/node_osrm-v5.27.1-node-v111-darwin-arm64-Release.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.27.1/node_osrm-v5.27.1-node-v111-darwin-arm64-Release.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /Users/mac/Desktop/backends/backend/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mac/Desktop/backends/backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /Users/mac/Desktop/backends/backend/node_modules/@project-osrm/osrm
npm ERR! node-pre-gyp ERR! node -v v19.0.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! CMake Warning:
npm ERR!   Ignoring extra path from command line:
npm ERR! 
npm ERR!    ".."
npm ERR! 
npm ERR! 
npm ERR! CMake Error: The source directory "/Users/mac/Desktop/backends/backend/node_modules/@project-osrm/osrm" does not appear to contain CMakeLists.txt.
npm ERR! Specify --help for usage, or press the help button on the CMake GUI.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2022-10-31T19_25_01_225Z-debug-0.log
```

**Comment by SiarheiFedartsou** [comment]
Which version of Node are you using?

**Comment by SiarheiFedartsou** [comment]
I see, it is v19.0.0. Can you try it on current LTS, i.e. 18? You can try nvm to easily switch between node versions https://github.com/nvm-sh/nvm

**Comment by KaSakee** [comment]
> I see, it is v19.0.0. Can you try it on current LTS, i.e. 18? You can try nvm to easily switch between node versions https://github.com/nvm-sh/nvm

I tried it on various versions, stable, latest, and previous, and all produced the same issue.

**Comment by SiarheiFedartsou** [comment]
> > I see, it is v19.0.0. Can you try it on current LTS, i.e. 18? You can try nvm to easily switch between node versions https://github.com/nvm-sh/nvm
> 
> I tried it on various versions, stable, latest, and previous, and all produced the same issue.

Could you provide your output on Node v18?

**Comment by KaSakee** [comment]
> > > I see, it is v19.0.0. Can you try it on current LTS, i.e. 18? You can try nvm to easily switch between node versions https://github.com/nvm-sh/nvm
> > 
> > 
> > I tried it on various versions, stable, latest, and previous, and all produced the same issue.
> 
> Could you provide your output on Node v18?

`npm install @project-osrm/osrm@5.27.1 --save` or `npm install @project-osrm/osrm--save`

On macOS Ventura M1 (Apple Silicon)


```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/mac/Desktop/backends/backend/node_modules/osrm
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
npm ERR! response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz
npm ERR! ~/Desktop/backends/backend/node_modules/osrm/build ~/Desktop/backends/backend/node_modules/osrm
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.12.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/mac/Desktop/backends/backend/node_modules/osrm/lib/binding/node_osrm.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/Project-OSRM/osrm-backend/releases/download/v5.26.0/node_osrm-v5.26.0-node-v108-darwin-arm64-Release.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /Users/mac/Desktop/backends/backend/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mac/Desktop/backends/backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /Users/mac/Desktop/backends/backend/node_modules/osrm
npm ERR! node-pre-gyp ERR! node -v v18.12.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! CMake Warning:
npm ERR!   Ignoring extra path from command line:
npm ERR! 
npm ERR!    ".."
npm ERR! 
npm ERR! 
npm ERR! CMake Error: The source directory "/Users/mac/Desktop/backends/backend/node_modules/osrm" does not appear to contain CMakeLists.txt.
npm ERR! Specify --help for usage, or press the help button on the CMake GUI.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2022-10-31T21_17_14_122Z-debug-0.log
```

**Comment by SiarheiFedartsou** [comment]
@KaSakee if you look into your output you are still installing 5.26.0(but not 5.27.1 which has support for M1)

**Comment by SiarheiFedartsou** [comment]
I can guess that may be it tries to install old node_osrm module which you forgot to remove(technically `@project-osrm/osrm` is completely new module)

**Comment by KaSakee** [comment]
> @KaSakee if you look into your output you are still installing 5.26.0(but not 5.27.1 which has support for M1)

I've seen it. That is why I am providing the command I used.

I have deleted the old OSRM from my project and package.json

Commands I used:

`npm install @project-osrm/osrm@5.27.1 --save` & `npm install @project-osrm/osrm --save`

**Comment by SiarheiFedartsou** [comment]
I use M1 too and just installed OSRM in fresh project without any errors.
```
mkdir testnpm
cd testnpm
npm init # just press enter on all questions
npm install @project-osrm/osrm@5.27.1 --save
```

```
➜  testnpm node --version
v18.7.0
```

Could you try on new project? May be you have something cached in your existing project?

**Comment by KaSakee** [comment]
> 

That was great. Something must be cached in my project. After double-checking, I deleted node modules, npm caches, and OSRM from the package. JSON, That's odd. I'll try to fix the mistakes in my project.

Thank you very much!

**Comment by SiarheiFedartsou** [comment]
You are welcome, I am closing the issue, but feel free to ask further questions or re-open issue if needed.

**Comment by KaSakee** [comment]
In case anyone is interested in how I fixed it,

"isochrone" was an npm package I had. 
It uses OSRM beneath the hood, so the package's OSRM version is 5.26.0. That is why it failed. It was attempting to install the previous version of the package.


The moral of the story is that if you encounter something similar, check to see if you are using another package that is utilizing an older version of your required package.
