### ISSUE TITLE
Problem initialising the routing machine on Android device

### ISSUE THREAD

**Issue by tniira** [Project-OSRM/osrm-backend#6688]
Background info:

- osrm-backend "latest" (5.28.0-unreleased) compiled and linked for Android as JNI library
- map data: finland-latest.osm.pbf pre-processed with "latest" osrm-extract, osrm-partition and osrm-customize

As a result of map data pre-processing there will be files as follows

```
-rw-r--r--   1 dev  staff  591183485 Aug 29 04:31 finland-latest.osm.pbf
-rw-r--r--   1 dev  staff  430696448 Aug 29 08:36 finland-latest.osrm
-rw-r--r--   1 dev  staff  137266176 Aug 29 08:43 finland-latest.osrm.cell_metrics
-rw-r--r--   1 dev  staff    1795072 Aug 29 08:42 finland-latest.osrm.cells
-rw-r--r--   1 dev  staff   23057408 Aug 29 08:37 finland-latest.osrm.cnbg
-rw-r--r--   1 dev  staff   23057408 Aug 29 08:42 finland-latest.osrm.cnbg_to_ebg
-rw-r--r--   1 dev  staff      69632 Aug 29 08:43 finland-latest.osrm.datasource_names
-rw-r--r--   1 dev  staff  123310592 Aug 29 08:42 finland-latest.osrm.ebg
-rw-r--r--   1 dev  staff   34673152 Aug 29 08:42 finland-latest.osrm.ebg_nodes
-rw-r--r--   1 dev  staff   35976192 Aug 29 08:38 finland-latest.osrm.edges
-rw-r--r--   1 dev  staff   33780224 Aug 29 08:42 finland-latest.osrm.enw
-rwxr--r--   1 dev  staff  177654040 Aug 29 08:42 finland-latest.osrm.fileIndex
-rw-r--r--   1 dev  staff  181381120 Aug 29 08:38 finland-latest.osrm.geometry
-rw-r--r--   1 dev  staff   34994688 Aug 29 08:38 finland-latest.osrm.icd
-rw-r--r--   1 dev  staff       5120 Aug 29 08:42 finland-latest.osrm.maneuver_overrides
-rw-r--r--   1 dev  staff  130622976 Aug 29 08:43 finland-latest.osrm.mldgr
-rw-r--r--   1 dev  staff    1801216 Aug 29 08:36 finland-latest.osrm.names
-rw-r--r--   1 dev  staff  106929664 Aug 29 08:37 finland-latest.osrm.nbg_nodes
-rw-r--r--   1 dev  staff   22527488 Aug 29 08:42 finland-latest.osrm.partition
-rw-r--r--   1 dev  staff       6144 Aug 29 08:36 finland-latest.osrm.properties
-rw-r--r--   1 dev  staff     713728 Aug 29 08:38 finland-latest.osrm.ramIndex
-rw-r--r--   1 dev  staff       4096 Aug 29 08:37 finland-latest.osrm.restrictions
-rw-r--r--   1 dev  staff       3584 Aug 29 08:32 finland-latest.osrm.timestamp
-rw-r--r--   1 dev  staff       5120 Aug 29 08:38 finland-latest.osrm.tld
-rw-r--r--   1 dev  staff       7680 Aug 29 08:38 finland-latest.osrm.tls
-rw-r--r--   1 dev  staff   10278912 Aug 29 08:37 finland-latest.osrm.turn_duration_penalties
-rw-r--r--   1 dev  staff   61655040 Aug 29 08:37 finland-latest.osrm.turn_penalties_index
-rw-r--r--   1 dev  staff   10278912 Aug 29 08:37 finland-latest.osrm.turn_weight_penalties
```
All pre-processed files are then uploaded to Android device. The access rights seem to be fine according to Android Studio Device File Manager and also according to execution debug log, the file(s) seem to be readable in the device.

The C++ code that consumes the map files is like follows

```
    EngineConfig engineConfig;
    engineConfig.algorithm = EngineConfig::Algorithm::MLD;
    engineConfig.max_locations_distance_table = 500;
    engineConfig.max_alternatives = 3;

   const char *nativePath = env->GetStringUTFChars(path, JNI_FALSE);        
   std::string filePath = nativePath;
   __android_log_print(ANDROID_LOG_DEBUG, "native-lib", "%s", filePath.c_str());
   engineConfig.storage_config = storage::StorageConfig(nativePath); 
 
  if (fileExists(filePath)) 
       __android_log_print(ANDROID_LOG_DEBUG, "native-lib", "FILE EXISTS");
   else
       __android_log_print(ANDROID_LOG_DEBUG, "native-lib", "FILE DOES NOT EXIST");

   __android_log_print(ANDROID_LOG_DEBUG, "native-lib", "Starting OSRM engine...");
   __android_log_print(ANDROID_LOG_DEBUG, "native-lib", "...engine using disk based access to data files!");
   OSRM* routing_machine = new OSRM(engineConfig); 
   __android_log_print(ANDROID_LOG_DEBUG, "native-lib", "Created OSRM engine using disk based access to data files");
```

When above code is executed it in Android emulator fails as seen on the device log:

```
FILE EXISTS
Starting OSRM engine...
...engine using disk based access to data files!

Shutting down VMFATAL EXCEPTION: main
Process: com.example.osrmnative, PID: 30248
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.osrmnative/com.example.osrmnative.MainActivity}: java.lang.Exception: Required files are missing, cannot continue. Have all the pre-processing steps been run? Missing files: /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.ramIndex, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.fileIndex, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.edges, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.geometry, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.turn_weight_penalties, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.turn_duration_penalties, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.datasource_names, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.names, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.timestamp, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.properties, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.icd, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.maneuver_overrides
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.Exception: Required files are missing, cannot continue. Have all the pre-processing steps been run? Missing files: /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.ramIndex, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.fileIndex, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.edges, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.geometry, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.turn_weight_penalties, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.turn_duration_penalties, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.datasource_names, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.names, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.timestamp, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.properties, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.icd, /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.maneuver_overrides
	at com.redacted.osrmbinding.OSRMBinding.init(Native Method)
	at com.redacted.osrmbinding.OSRMBinding.<init>(OSRMBinding.java:67)
	at com.example.osrmnative.MainActivity.onCreate(MainActivity.kt:46)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)

```

As one can see that it complains the some map files are missing **BUT** those missing file name **are different** than those produced by pre-processing tools. An example:
```
Missing files: /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.ramIndex, 
```
vs.
```
-rw-r--r--   1 dev  staff     713728 Aug 29 08:38 finland-latest.osrm.ramIndex
```

Note the extra **.osrm.** in missing file name error!

Any ideas what is going wrong here? I have done similar thing with version 5.26-0 targeting on Linux and I did not face this kind of issues.

The underlying environment is macOS if it has any relevance.

Thanks!

**Comment by jcoupey** [comment]
The plain `*.osrm` file has been removed recently from the workflow but you have a `finland-latest.osrm`. So it looks as if you're using osrm data processed with an older version.

The osrm files are usually not compatible across versions, meaning the problem may simply vanish is you do the data processing and routing with the same OSRM version.

**Comment by tniira** [comment]
OSRM data was process using tools provide by a Docker image:
--
docker pull osrm/osrm-backend
Using default tag: latest
latest: Pulling from osrm/osrm-backend
aed007321795: Pull complete 
595e916ac67a: Pull complete 
69f309e04f11: Pull complete 
e73ad3e5bcf3: Pull complete 
4c20f809069e: Pull complete 
Digest: sha256:af5d4a83fb90086a43b1ae2ca22872e6768766ad5fcbb07a29ff90ec644ee409
Status: Downloaded newer image for osrm/osrm-backend:latest
docker.io/osrm/osrm-backend:latest
--
So Docker is stating **latest**... Isn't the Docker **latest** same as backend source latest?

**Comment by jcoupey** [comment]
You may have better luck pinning an actual release version for your whole workflow. On a side note, there is no guarantee that the file preprocessed on a given machine will be compatible to run the routing on another.

**Comment by arnesetzer** [comment]
The docker images moved from docker hub to github a few years ago. So you need to execute `docker pull ghcr.io/project-osrm/osrm-backend` to get the latest docker image. This is mentioned in the [Readme](https://github.com/Project-OSRM/osrm-backend#using-docker) as well.

**Comment by tniira** [comment]
Yes, in the end,  there was a clear incompatibility issue with the engine and the map files. BUT the engine actually  never reached to check it as it strangely manipulates the given path at Android device:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.osrmnative/com.example.osrmnative.MainActivity}: java.lang.Exception: Required files are missing, cannot continue.`

=>

`Missing files: /data/user/0/com.examplenative/files/osrm-map/finland-car/finland-latest.osrm.osrm.ramIndex,`

So  **com.example.osrmnative** becomes **com.examplenative** which is a clear bug.

Once the package name is refactored to something else (like com.example.foobar) the engine finds the map files and correctly informs about the map incompatibility issue.

**Comment by jcoupey** [comment]
Glad you figured it out, closing as solved.
